version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db_postgres
    ports:
      - "5432:5432"
    volumes:
      - volume_postgres:/var/lib/postgresql/data

volumes:
  volume_postgres:
